const fs = require('fs');
const path = require('path');
const { imageSize } = require('image-size');

const staticDir = path.join(__dirname, '..', 'static');
const figuresDir = path.join(staticDir, 'figures');
const outputFile = path.join(__dirname, '..', 'src', 'imageDimensions.js');

const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp']);

// Recursively collect all image files
function collectImages(dir, results = []) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectImages(fullPath, results);
    } else if (IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      results.push(fullPath);
    }
  }
  return results;
}

// Main
const images = collectImages(figuresDir);
const dimensions = {};
let successCount = 0;
let errorCount = 0;

for (const imgPath of images) {
  // Key = path relative to static/, with forward slashes (matches src prop in MDX)
  const relPath = path.relative(staticDir, imgPath).replace(/\\/g, '/');
  try {
    const buffer = fs.readFileSync(imgPath);
    const result = imageSize(buffer);
    if (result.width && result.height) {
      dimensions[relPath] = { width: result.width, height: result.height };
      successCount++;
    } else {
      console.warn(`⚠️ No dimensions found for ${relPath}`);
      errorCount++;
    }
  } catch (err) {
    console.warn(`⚠️ Could not read dimensions for ${relPath}: ${err.message}`);
    errorCount++;
  }
}

// Write as a JS module (same pattern as src/reportIdMap.js)
const output = `// Auto-generated by scripts/generateImageDimensions.js — DO NOT EDIT\nmodule.exports = ${JSON.stringify(dimensions, null, 2)};\n`;
fs.writeFileSync(outputFile, output);

console.log(`✅ Image dimensions: ${successCount} images processed, ${errorCount} errors → ${outputFile}`);
